OIDC Integration for all ENVs
exporo/central-workflows pull request #23
Opened 2023-05-22 11:08 UTC by teja-srinivas

2023-05-23 09:53 UTC, robertpranjic commented
hey Teja, overall it looks good
but are we sure this is not gonna break anything?

I would prefer an "expand and contract" / "blue-green" type of approach

1. Create a new workflow that contains OIDC
2. Change the implementations inside the repos to the new workflow
3. Remove the old workflow if everything works as expected

2023-05-23 09:53 UTC, robertpranjic requested changes
Wrote a comment regarding blue-green rollout

2023-10-27 10:54 UTC, lsdomingos approved these changes
@teja-srinivas from my perspective is good, but it would be nice to have this tessted. We need to rename the file CICDwithOIDC to CICD or merge tit like this to some how trigger the new pipeline and test

2023-11-02 15:08 UTC, lsdomingos approved these changes

2023-11-02 15:08 UTC, merged